x-pg-envs:
  &pg_envs
  POSTGRES_USER: monitoring_local
  POSTGRES_PASSWORD: monitoring_local
  POSTGRES_DB: monitoring_local
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432


services:
  postgres:
    image: docker-proxy.artifactory.tcsbank.ru/postgres:15
    ports:
      - "5432:5432"
    environment:
      <<: *pg_envs
